/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prolab;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emrea
 */
public class araccikarmaPanel extends javax.swing.JFrame {


    /**
     * Creates new form araccikarmaPanel
     */
    public araccikarmaPanel() {
        
        initComponents();
        mevcutaraclarigoruntule();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("ARAÇ ÇIKARMA PANELİ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sirketpanelinedon = new javax.swing.JButton();
        araccikar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mevcutaraclar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(380, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        sirketpanelinedon.setBackground(new java.awt.Color(51, 0, 51));
        sirketpanelinedon.setText("ŞİRKET PANELİNE GERİ DÖN");
        sirketpanelinedon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sirketpanelinedonActionPerformed(evt);
            }
        });

        araccikar.setBackground(new java.awt.Color(51, 0, 51));
        araccikar.setText("SEÇİLİ ARAÇ ÇIKAR");
        araccikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araccikarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("MEVCUT ARAÇLAR");

        mevcutaraclar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mevcutaraclar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ARAÇ İD", "KOLTUK SAYISI", "ARAÇ TİPİ", "VAR OLAN SEFER GÜNLERİ VE SEFER NUMARASI"
            }
        ));
        jScrollPane3.setViewportView(mevcutaraclar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sirketpanelinedon, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                                    .addComponent(araccikar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(araccikar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sirketpanelinedon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void araccikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araccikarActionPerformed

        int seciliaracrow = mevcutaraclar.getSelectedRow();
        main1.secili.getAraclar().remove(seciliaracrow);
        this.dispose();

    }//GEN-LAST:event_araccikarActionPerformed

    private void sirketpanelinedonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sirketpanelinedonActionPerformed

        this.dispose();
    }//GEN-LAST:event_sirketpanelinedonActionPerformed

        public void mevcutaraclarigoruntule(){

    
        DefaultTableModel model = (DefaultTableModel) mevcutaraclar.getModel();
        int i= 0;
        for (Vehicle arac:main1.secili.getAraclar()) {

            String ismi = String.valueOf(   arac.getId());
            String turu = "";
            
            String gunlerveseferleri = "";
            
            
            for(Trip t: arac.getSeferler()){
                
                gunlerveseferleri +=  t.getTime()+":"+t.getGuzergahnum()+"-";

            }
            
            
            if(arac instanceof Bus){
                turu = "OTOBUS";
            }else if(arac instanceof  Airplane){
                turu = "UCAK";
            }else{
                turu = "TREN";
            }
             
            
            
          
             model.setValueAt(ismi,i,0); // ürün ismi.
             model.setValueAt(String.valueOf(arac.getYolcusayisi()), i, 1);
                         model.setValueAt(turu,i,2); 
                                      model.setValueAt(gunlerveseferleri,i,3); // seferleri...
                     
            i++;
        }

        
        
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(araccikarmaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(araccikarmaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(araccikarmaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(araccikarmaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new araccikarmaPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton araccikar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable mevcutaraclar;
    private javax.swing.JButton sirketpanelinedon;
    // End of variables declaration//GEN-END:variables

    private void verilerigoruntule() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
