/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prolab;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emrea
 */
public class araceklemePanel extends javax.swing.JFrame {

    /**
     * Creates new form araceklemePanel
     */
    
    public Company secili = null;
    
    
    
    public araceklemePanel() {

        initComponents();
        secili = main1.secili;
        mevcutaraclarigoruntule();
        firmaadi.setText(secili.getKullaniciadi() + " FİRMASI");
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liste1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        koltuksayisi = new javax.swing.JTextField();
        anadon = new javax.swing.JButton();
        aracekle = new javax.swing.JButton();
        uyari = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firmaadi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tarihcombo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        mevcutaraclar = new javax.swing.JTable();
        yakitucreti = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        yakitcombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        anperucret = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        yarperucret = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(380, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        liste1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        liste1.setForeground(new java.awt.Color(0, 0, 0));
        liste1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1.sefer Demiryolu: Istanbul - Kocaeli - Bilecik - Eskisehir - Ankara - Eskisehir - Bilecik - Kocaeli - Istanbul", "2.sefer Demiryolu: Istanbul - Kocaeli - Bilecik - Eskişehir - Konya - Eskisehir - Bilecik - Kocaeli - Istanbul", "3.sefer Karayolu: Istanbul - Kocaeli - Ankara - Kocaeli - Istanbul - Kocaeli - Ankara - Kocaeli - Istanbul", "4.sefer Karayolu: Istanbul - Kocaeli - Eskisehir - Konya - Eskisehir - Kocaeli- Istanbul", "5.sefer Havayolu: Istanbul - Konya - Istanbul", "6.sefer Havayolu: ˙Istanbul - Ankara - Istanbul" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(liste1);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SEFER SEÇİMİ (ARAÇ SEÇİME GÖRE OTOMATİK OLUŞACAKTIR)");

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("KOLTUK SAYISI");

        anadon.setBackground(new java.awt.Color(204, 0, 0));
        anadon.setForeground(new java.awt.Color(0, 255, 255));
        anadon.setText("ANA MENÜYE DÖN");
        anadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadonActionPerformed(evt);
            }
        });

        aracekle.setBackground(new java.awt.Color(204, 0, 0));
        aracekle.setForeground(new java.awt.Color(0, 255, 255));
        aracekle.setText("ARAÇ EKLE");
        aracekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aracekleActionPerformed(evt);
            }
        });

        uyari.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        uyari.setForeground(new java.awt.Color(255, 0, 51));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("MEVCUT ARAÇLAR");

        firmaadi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firmaadi.setForeground(new java.awt.Color(255, 0, 0));

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("SEFERİN GÜNÜ");

        tarihcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 ARALIK", "5 ARALIK", "6 ARALIK", "7 ARALIK", "8 ARALIK", "9 ARALIK", "10 ARALIK" }));
        tarihcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihcomboActionPerformed(evt);
            }
        });

        mevcutaraclar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mevcutaraclar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ARAÇ İD", "KOLTUK SAYISI", "ARAÇ TİPİ VE YAKIT TÜRÜ", "VAR OLAN SEFER GÜNLERİ VE SEFER NUMARASI"
            }
        ));
        jScrollPane3.setViewportView(mevcutaraclar);

        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("YAKIT ÜCRETİ");

        yakitcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "benzin", "mazot", "gaz", "elektrik", " " }));
        yakitcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yakitcomboActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("YAKIT TÜRÜ");

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("ANA PERSONEL UCRETİ");

        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("YARDIMCI PERSONEL UCRETİ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aracekle, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anadon, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(uyari, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(firmaadi, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(koltuksayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tarihcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anperucret, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yakitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yakitucreti, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yarperucret, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firmaadi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(koltuksayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yakitucreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarihcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yakitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anperucret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yarperucret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(uyari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aracekle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anadon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadonActionPerformed
    this.dispose();

    }//GEN-LAST:event_anadonActionPerformed
        public void mevcutaraclarigoruntule(){

    
        DefaultTableModel model = (DefaultTableModel) mevcutaraclar.getModel();
        int i= 0;
        for (Vehicle arac:main1.secili.getAraclar()) {

            String ismi = String.valueOf( arac.getId());
            String turu = "";
            
            String gunlerveseferleri = "";
            
            
            for(Trip t: arac.getSeferler()){
                
                gunlerveseferleri +=  t.getTime()+":"+t.getGuzergahnum()+"-";

            }
            
            
            if(arac instanceof Bus){
                turu = "OTOBUS";
            }else if(arac instanceof  Airplane){
                turu = "UCAK";
            }else{
                turu = "TREN";
            }

            
             model.setValueAt(ismi,i,0); // ürün ismi.
             model.setValueAt(String.valueOf(arac.getYolcusayisi()), i, 1);
                         model.setValueAt(turu + " "+arac.getYakitturu().toUpperCase(),i,2); 
                                      model.setValueAt(gunlerveseferleri,i,3); // seferleri...
                     
            i++;
        }
        }
    
    private void aracekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aracekleActionPerformed
       
        if ("".equals(this.koltuksayisi.getText())) {
            uyari.setText("KOLTUK SAYİSİ BOS...");
            return;
        }
        
        int yakitfiyatitext = Integer.parseInt(yakitucreti.getText());
        int anapersonelucreti = Integer.parseInt(anperucret.getText());
                int yardimcipersonelucreti = Integer.parseInt(yarperucret.getText());
                String yakitturu = (String)yakitcombo.getSelectedItem();
                
        int koltuksayisi = Integer.parseInt(this.koltuksayisi.getText());
        int secilisefer = liste1.getSelectedIndex() + 1;
        int seciliseferingunu = tarihcombo.getSelectedIndex() + 1;

        if (secilisefer == 0 || secilisefer == 1) {

            
            Train tren = new Train(main1.aracid++, yakitfiyatitext, koltuksayisi );
            tren.setYakitturu(yakitturu);
            
                        tren.seferekle(secilisefer, seciliseferingunu);

                                                                            tren.calisanekle(new Personel("AA","AA",anapersonelucreti));
    tren.calisanekle(new Personel("BB","BB",anapersonelucreti));
    tren.calisanekle(new Personel("CC","CC",yardimcipersonelucreti));
    tren.calisanekle(new Personel("DD","DD",yardimcipersonelucreti));   
            

            secili.aracekle(tren);
            
        }else if (secilisefer == 2 || secilisefer == 3) {


            Bus otobus  = new Bus(main1.aracid++, yakitfiyatitext, koltuksayisi);
            otobus.seferekle(secilisefer, seciliseferingunu);
            otobus.setYakitturu(yakitturu);
                                                    otobus.calisanekle(new Personel("AA","AA",anapersonelucreti));
    otobus.calisanekle(new Personel("BB","BB",anapersonelucreti));
    otobus.calisanekle(new Personel("CC","CC",yardimcipersonelucreti));
    otobus.calisanekle(new Personel("DD","DD",yardimcipersonelucreti));   
            
            
            
            secili.aracekle(otobus);
            
        }else if(secilisefer == 4 || secilisefer == 5){

        
            Airplane ucak = new Airplane(main1.aracid++, yakitfiyatitext, koltuksayisi);
            ucak.seferekle(secilisefer, seciliseferingunu);
            ucak.setYakitturu(yakitturu);
                                                    ucak.calisanekle(new Personel("AA","AA",anapersonelucreti));
    ucak.calisanekle(new Personel("BB","BB",anapersonelucreti));
    ucak.calisanekle(new Personel("CC","CC",yardimcipersonelucreti));
    ucak.calisanekle(new Personel("DD","DD",yardimcipersonelucreti));
    
            
            
            secili.aracekle(ucak);
            
            
        }else{
            uyari.setText("SEÇİLİ SEFER YOK...");
        }
        
       this.dispose();
        
        
    }//GEN-LAST:event_aracekleActionPerformed

    private void tarihcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihcomboActionPerformed

    private void yakitcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yakitcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yakitcomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(araceklemePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(araceklemePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(araceklemePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(araceklemePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new araceklemePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadon;
    private javax.swing.JTextField anperucret;
    private javax.swing.JButton aracekle;
    private javax.swing.JLabel firmaadi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField koltuksayisi;
    private javax.swing.JList<String> liste1;
    private javax.swing.JTable mevcutaraclar;
    private javax.swing.JComboBox<String> tarihcombo;
    private javax.swing.JLabel uyari;
    private javax.swing.JComboBox<String> yakitcombo;
    private javax.swing.JTextField yakitucreti;
    private javax.swing.JTextField yarperucret;
    // End of variables declaration//GEN-END:variables
}
