/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prolab;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emrea
 */
public class firmasilmePanel extends javax.swing.JFrame {

    /**
     * Creates new form firmasilmePanel
     */
    public firmasilmePanel() {
        
        initComponents();
        
        verilerigoruntule();
        
        setTitle("FİRMA SİLME PANELİ");
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        notbelirleme.setText("");
        
        
    }
    
    public void verilerigoruntule(){
   
        DefaultTableModel model = (DefaultTableModel) firmatablosu.getModel();
        int i= 0;
        for (Company firmalar1 : main1.sirketler) {
            System.out.println("he");
            String ismi = firmalar1.getKullaniciadi();


            System.out.println(ismi);
            
             model.setValueAt(ismi,i,0); // ürün ismi.

            i++;
           
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        firmatablosu = new javax.swing.JTable();
        secilifirmasil = new javax.swing.JButton();
        adminpanelinedon = new javax.swing.JButton();
        notbelirleme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FİRMA SİLME PANELİ");
        setBounds(new java.awt.Rectangle(380, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        firmatablosu.setBackground(new java.awt.Color(0, 204, 204));
        firmatablosu.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        firmatablosu.setForeground(new java.awt.Color(0, 0, 153));
        firmatablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "FİRMA ADI"
            }
        ));
        firmatablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firmatablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(firmatablosu);

        secilifirmasil.setBackground(new java.awt.Color(204, 0, 51));
        secilifirmasil.setForeground(new java.awt.Color(0, 0, 153));
        secilifirmasil.setText("SEÇİLİ FİRMA SİL");
        secilifirmasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secilifirmasilActionPerformed(evt);
            }
        });

        adminpanelinedon.setBackground(new java.awt.Color(0, 0, 102));
        adminpanelinedon.setForeground(new java.awt.Color(255, 255, 0));
        adminpanelinedon.setText("ADMİN PANELİNE DÖN");
        adminpanelinedon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpanelinedonActionPerformed(evt);
            }
        });

        notbelirleme.setText("\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(notbelirleme, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(336, 336, 336)
                                .addComponent(secilifirmasil, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(adminpanelinedon, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secilifirmasil)
                .addGap(18, 18, 18)
                .addComponent(adminpanelinedon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(notbelirleme, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminpanelinedonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpanelinedonActionPerformed
        setVisible(false);
        adminPanel a = new adminPanel();
        a.setVisible(true);
        
    }//GEN-LAST:event_adminpanelinedonActionPerformed

    private void firmatablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firmatablosuMouseClicked
        

          
         
         
    }//GEN-LAST:event_firmatablosuMouseClicked

    private void secilifirmasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secilifirmasilActionPerformed
         DefaultTableModel model = (DefaultTableModel) firmatablosu.getModel(); // bir model kurarız bu yapı ile...
         
         int secilirow = firmatablosu.getSelectedRow();
         if (secilirow == -1) {
             System.out.println("SECİM YOK");
        }
         
         
         main1.sirketler.remove(secilirow);
         
         firmasilmePanel fs = new firmasilmePanel();
         fs.setVisible(true);
         
         this.dispose();
    
         

    }//GEN-LAST:event_secilifirmasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firmasilmePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firmasilmePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firmasilmePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firmasilmePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firmasilmePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminpanelinedon;
    private javax.swing.JTable firmatablosu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel notbelirleme;
    private javax.swing.JButton secilifirmasil;
    // End of variables declaration//GEN-END:variables
}
