/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prolab;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emrea
 */
public class sefercikarmaPanel extends javax.swing.JFrame {

    
            public void mevcutaraclarigoruntule(){

    
        DefaultTableModel model = (DefaultTableModel) mevcutaraclar.getModel();
        int i= 0;
        for (Vehicle arac:main1.secili.getAraclar()) {

            String ismi = String.valueOf(   arac.getId());
            String turu = "";
            
            String gunlerveseferleri = "";
            
            
            for(Trip t: arac.getSeferler()){
                
                gunlerveseferleri +=  t.getTime()+":"+t.getGuzergahnum()+"-";

            }
            
            
            if(arac instanceof Bus){
                turu = "OTOBUS";
            }else if(arac instanceof  Airplane){
                turu = "UCAK";
            }else{
                turu = "TREN";
            }

           
             model.setValueAt(ismi,i,0); // ürün ismi.
                         model.setValueAt(turu,i,1); 
                                      model.setValueAt(gunlerveseferleri,i,2); // seferleri...
                     
            i++;
        }
        
        

        
        
        
        
    }
    
    
    /**
     * Creates new form sefercikarmaPanel
     */
    public sefercikarmaPanel() {
        initComponents();
        setTitle("SEFER ÇIKARMA PANELİ");
        mevcutaraclarigoruntule();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        seferiekle = new javax.swing.JButton();
        firmapaneldon = new javax.swing.JButton();
        uyari = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mevcutaraclar = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tarihcombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(380, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        seferiekle.setBackground(new java.awt.Color(0, 0, 153));
        seferiekle.setForeground(new java.awt.Color(255, 255, 0));
        seferiekle.setText("SEFERİ ÇIKAR");
        seferiekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seferiekleActionPerformed(evt);
            }
        });

        firmapaneldon.setBackground(new java.awt.Color(0, 0, 153));
        firmapaneldon.setForeground(new java.awt.Color(255, 255, 0));
        firmapaneldon.setText("FİRMA PANELİNE DÖN");
        firmapaneldon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firmapaneldonActionPerformed(evt);
            }
        });

        uyari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        uyari.setForeground(new java.awt.Color(255, 0, 0));

        mevcutaraclar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mevcutaraclar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ARAÇ İD", "ARAÇ TİPİ", "VAR OLAN SEFER GÜNLERİ VE SEFER NUMARASI"
            }
        ));
        jScrollPane3.setViewportView(mevcutaraclar);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("MEVCUT ARAÇLAR (ARAÇ SEÇİNİZ)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("SEFER ÇIKARILACAK GÜN SEÇİMİ");

        tarihcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 ARALIK", "5 ARALIK", "6 ARALIK", "7 ARALIK", "8 ARALIK", "9 ARALIK", "10 ARALIK" }));
        tarihcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihcomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seferiekle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firmapaneldon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tarihcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uyari, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tarihcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uyari, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seferiekle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firmapaneldon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seferiekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seferiekleActionPerformed
         
        
        int silinecekgun = tarihcombo.getSelectedIndex() + 1;
        int aracinki = mevcutaraclar.getSelectedRow();
        if(aracinki == -1){
            uyari.setText("ARAC SEÇİMİ YOK");
            return;
        }
        
        ArrayList<Trip> ar = main1.secili.getAraclar().get(aracinki).getSeferler();
        
        for (int i = 0; i < ar.size(); i++) {
            
                        if (ar.get(i).getTime() == silinecekgun) {
                ar.remove(i);
            }

            
        }
        this.dispose();
        /*
        
        for (Trip trip : ar) {
            
            if (trip.getTime() == silinecekgun) {
                ar.remove(trip);
            }
            
        }
        */
        
        
        

    }//GEN-LAST:event_seferiekleActionPerformed

    private void firmapaneldonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firmapaneldonActionPerformed
        this.dispose();

    }//GEN-LAST:event_firmapaneldonActionPerformed

    private void tarihcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihcomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sefercikarmaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sefercikarmaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sefercikarmaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sefercikarmaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sefercikarmaPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firmapaneldon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable mevcutaraclar;
    private javax.swing.JButton seferiekle;
    private javax.swing.JComboBox<String> tarihcombo;
    private javax.swing.JLabel uyari;
    // End of variables declaration//GEN-END:variables
}
