/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prolab;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emrea
 */
public class sefereklemePanel extends javax.swing.JFrame {

    /**
     * Creates new form sefereklemePanel
     */
    
    private Company sirket = null;

    public void firmaekleme(Company c){
        sirket = c;

    }
    

    
    
    public sefereklemePanel() {
        initComponents();
        mevcutaraclarigoruntule();
                setTitle("SEFER EKLEME PANELİ");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firmapaneldon = new javax.swing.JButton();
        seferiekle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        liste1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        mevcutaraclar = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tarihcombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        uyari = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(380, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        firmapaneldon.setBackground(new java.awt.Color(0, 0, 153));
        firmapaneldon.setForeground(new java.awt.Color(255, 255, 0));
        firmapaneldon.setText("FİRMA PANELİNE DÖN");
        firmapaneldon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firmapaneldonActionPerformed(evt);
            }
        });

        seferiekle.setBackground(new java.awt.Color(0, 0, 153));
        seferiekle.setForeground(new java.awt.Color(255, 255, 0));
        seferiekle.setText("SEFERİ EKLE");
        seferiekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seferiekleActionPerformed(evt);
            }
        });

        liste1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        liste1.setForeground(new java.awt.Color(0, 0, 0));
        liste1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1.sefer Demiryolu: Istanbul - Kocaeli - Bilecik - Eskisehir - Ankara - Eskisehir - Bilecik - Kocaeli - Istanbul", "2.sefer Demiryolu: Istanbul - Kocaeli - Bilecik - Eskişehir - Konya - Eskisehir - Bilecik - Kocaeli - Istanbul", "3.sefer Karayolu: Istanbul - Kocaeli - Ankara - Kocaeli - Istanbul - Kocaeli - Ankara - Kocaeli - Istanbul", "4.sefer Karayolu: Istanbul - Kocaeli - Eskisehir - Konya - Eskisehir - Kocaeli- Istanbul", "5.sefer Havayolu: Istanbul - Konya - Istanbul", "6.sefer Havayolu: ˙Istanbul - Ankara - Istanbul" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(liste1);

        mevcutaraclar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mevcutaraclar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ARAÇ İD", "KOLTUK SAYISI", "ARAÇ TİPİ", "VAR OLAN SEFER GÜNLERİ VE SEFER NUMARASI"
            }
        ));
        jScrollPane3.setViewportView(mevcutaraclar);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("MEVCUT ARAÇLAR (ARAÇ SEÇİNİZ)");

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("SEFERİN GÜNÜ");

        tarihcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 ARALIK", "5 ARALIK", "6 ARALIK", "7 ARALIK", "8 ARALIK", "9 ARALIK", "10 ARALIK" }));
        tarihcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihcomboActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SEFER SEÇİMİ");

        uyari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        uyari.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(firmapaneldon, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tarihcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seferiekle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uyari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarihcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(uyari, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seferiekle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firmapaneldon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seferiekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seferiekleActionPerformed
        
        int eklenecekgun = tarihcombo.getSelectedIndex() + 1;
        int seciliarac = mevcutaraclar.getSelectedRow();
        System.out.println(seciliarac);
        
        
        if (seciliarac == -1) {
            uyari.setText("SEÇİLİ ARAÇ YOK");
            return;
        }
        
        int sefersayisi = liste1.getSelectedIndex() + 1;
        if(sefersayisi == -1){

            uyari.setText("SEÇİLİ SEFER YOK");

        }
        
        main1.secili.getAraclar().get(seciliarac).seferekle(sefersayisi, eklenecekgun);
        
        this.dispose();
       
        
       
        
    }//GEN-LAST:event_seferiekleActionPerformed
    
        public void mevcutaraclarigoruntule(){

            
            
    
        DefaultTableModel model = (DefaultTableModel) mevcutaraclar.getModel();
        int i= 0;
        for (Vehicle arac:main1.secili.getAraclar()) {

            String ismi = String.valueOf(   arac.getId());
            String turu = "";
            
            String gunlerveseferleri = "";
            
            
            for(Trip t: arac.getSeferler()){
                
                gunlerveseferleri +=  t.getTime()+":"+t.getGuzergahnum()+"-";

            }
            
            
            if(arac instanceof Bus){
                turu = "OTOBUS";
            }else if(arac instanceof  Airplane){
                turu = "UCAK";
            }else{
                turu = "TREN";
            }

           
             model.setValueAt(ismi,i,0); // ürün ismi.
             model.setValueAt(String.valueOf(arac.getYolcusayisi()), i, 1);
                         model.setValueAt(turu,i,2); 
                                      model.setValueAt(gunlerveseferleri,i,3); // seferleri...
                     
            i++;
        }
 
        
        
        
    }
        
        
    private void firmapaneldonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firmapaneldonActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_firmapaneldonActionPerformed

    private void tarihcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihcomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sefereklemePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sefereklemePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sefereklemePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sefereklemePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sefereklemePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firmapaneldon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> liste1;
    private javax.swing.JTable mevcutaraclar;
    private javax.swing.JButton seferiekle;
    private javax.swing.JComboBox<String> tarihcombo;
    private javax.swing.JLabel uyari;
    // End of variables declaration//GEN-END:variables
}
